# Generated by Django 5.2.3 on 2025-07-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0002_remove_image_url_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productseo',
            name='meta_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
