# Generated by Django 5.2.3 on 2025-07-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0003_alter_productseo_meta_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
    ]
