# Generated by Django 5.2.3 on 2025-07-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0004_remove_productimage_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='productseo',
            name='custom_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productseo',
            name='grouped_filters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
