# Generated by Django 5.2.3 on 2025-07-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0006_cart_device_uuid_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='device_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
