# Generated by Django 5.2.3 on 2025-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0008_remove_orders_user_orders_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrole',
            name='access_pages',
            field=models.JSONField(default=list),
        ),
    ]
