# Generated by Django 5.2.4 on 2025-08-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0010_firstcarousel_secondcarousel_firstcarouselimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_image', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('schema_enabled', models.BooleanField(default=False)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='admin_backend_final.blog')),
            ],
        ),
    ]
