# Generated by Django 5.2.4 on 2025-08-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0011_blogseo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='category',
        ),
    ]
