# Generated by Django 5.2.4 on 2025-08-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0013_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
