# Generated by Django 5.2.4 on 2025-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0015_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstcarouselimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='firstcarouselimage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='secondcarouselimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='secondcarouselimage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
