# Generated by Django 5.2.4 on 2025-08-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0017_category_caption_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='role_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('visible', 'Visible')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='deleteditemscache',
            name='table_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='herobannerimage',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='linked_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='linked_page',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='linked_table',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='zip_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='stock_status',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='canonical_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='image_alt_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='json_ld',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='open_graph_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='open_graph_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productseo',
            name='open_graph_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='add_on_options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='fabric_finish',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='material_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='printing_methods',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('visible', 'Visible')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='blogcategorymap',
            unique_together={('blog', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='categorysubcategorymap',
            unique_together={('category', 'subcategory')},
        ),
        migrations.AlterUniqueTogether(
            name='productsubcategorymap',
            unique_together={('product', 'subcategory')},
        ),
        migrations.AddIndex(
            model_name='adminrolemap',
            index=models.Index(fields=['admin'], name='admin_backe_admin_i_28e7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminrolemap',
            index=models.Index(fields=['role'], name='admin_backe_role_id_198918_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysubcategorymap',
            index=models.Index(fields=['category'], name='admin_backe_categor_542279_idx'),
        ),
        migrations.AddIndex(
            model_name='categorysubcategorymap',
            index=models.Index(fields=['subcategory'], name='admin_backe_subcate_36cce4_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategorymap',
            index=models.Index(fields=['product'], name='admin_backe_product_b23fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategorymap',
            index=models.Index(fields=['subcategory'], name='admin_backe_subcate_c8e19f_idx'),
        ),
    ]
