# Generated by Django 5.2.4 on 2025-08-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0019_cartitem_attributes_price_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstcarouselimage',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_carousel_images', to='admin_backend_final.category'),
        ),
        migrations.AddField(
            model_name='secondcarouselimage',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_carousel_images', to='admin_backend_final.category'),
        ),
        migrations.CreateModel(
            name='ProductThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_backend_final.productimage')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='admin_backend_final.product')),
            ],
        ),
    ]
