# Generated by Django 5.2.4 on 2025-08-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0020_firstcarouselimage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductThumbnail',
        ),
    ]
