# Generated by Django 5.2.4 on 2025-08-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0021_productimage_is_primary_delete_productthumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstcarouselimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='secondcarouselimage',
            name='category',
        ),
        migrations.AddField(
            model_name='firstcarouselimage',
            name='subcategory',
            field=models.ForeignKey(blank=True, db_column='subcategory_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_carousel_images', to='admin_backend_final.subcategory'),
        ),
        migrations.AddField(
            model_name='secondcarouselimage',
            name='subcategory',
            field=models.ForeignKey(blank=True, db_column='subcategory_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_carousel_images', to='admin_backend_final.subcategory'),
        ),
    ]
