# Generated by Django 5.2.4 on 2025-08-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0024_alter_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productseo',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=511),
        ),
    ]
