# Generated by Django 5.2.4 on 2025-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0025_remove_productseo_slug_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='device_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
