# Generated by Django 5.2.4 on 2025-09-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0029_product_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
    ]
