# Generated by Django 5.2.4 on 2025-09-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0030_image_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
    ]
