# Generated by Django 5.2.4 on 2025-09-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0031_remove_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
    ]
