# Generated by Django 5.2.4 on 2025-09-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0032_productimage_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogSEO',
        ),
    ]
