# Generated by Django 5.2.4 on 2025-09-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0033_delete_blogseo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategoryMap',
        ),
    ]
