# Generated by Django 5.2.4 on 2025-09-12 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0037_blogpost_blogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(db_column='blog_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admin_backend_final.blogpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blog'], name='admin_backe_blog_id_57a798_idx'), models.Index(fields=['created_at'], name='admin_backe_created_f0206e_idx')],
            },
        ),
    ]
