# Generated by Django 5.2.4 on 2025-09-16 17:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0038_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(db_index=True, default=5, help_text='Whole-star rating from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_by_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User')], default='admin', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_avatars', to='admin_backend_final.image')),
            ],
            options={
                'ordering': ['order', '-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='admin_backe_status_f2c13d_idx'), models.Index(fields=['rating'], name='admin_backe_rating_5cb428_idx'), models.Index(fields=['created_at'], name='admin_backe_created_0b93d4_idx')],
            },
        ),
    ]
