# Generated by Django 5.2.4 on 2025-09-19 13:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0039_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTestimonial',
            fields=[
                ('testimonial_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('rating', models.FloatField(db_index=True, default=0.0, help_text='Allowed values: 0, 0.5, 1, ... , 5', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('rating_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='admin_backend_final.product')),
                ('subcategory', models.ForeignKey(blank=True, db_column='subcategory_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='admin_backend_final.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='admin_backe_product_7a131f_idx'), models.Index(fields=['subcategory'], name='admin_backe_subcate_59bdb9_idx'), models.Index(fields=['status'], name='admin_backe_status_d4ad47_idx'), models.Index(fields=['rating'], name='admin_backe_rating_4f7ad9_idx'), models.Index(fields=['created_at'], name='admin_backe_created_2992c8_idx')],
            },
        ),
    ]
