# Generated by Django 5.2.4 on 2025-09-19 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0040_producttestimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeSubCategory',
            fields=[
                ('attribute_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('material', 'Material'), ('custom', 'Custom')], db_index=True, default='custom', max_length=50)),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], db_index=True, default='visible', max_length=20)),
                ('values', models.JSONField(blank=True, default=list)),
                ('subcategory_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='admin_backe_slug_c51f83_idx'), models.Index(fields=['status'], name='admin_backe_status_7aefbb_idx'), models.Index(fields=['type'], name='admin_backe_type_6c12e2_idx')],
            },
        ),
    ]
