# Generated by Django 5.2.4 on 2025-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0041_attributesubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributesubcategory',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='attributesubcategory',
            name='admin_backe_slug_c51f83_idx',
        ),
        migrations.RemoveIndex(
            model_name='attributesubcategory',
            name='admin_backe_status_7aefbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='attributesubcategory',
            name='admin_backe_type_6c12e2_idx',
        ),
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attributesubcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
