# Generated by Django 5.2.4 on 2025-09-25 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0042_alter_attributesubcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('branding_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('site_title', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one active branding is allowed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favicon', models.ForeignKey(blank=True, db_column='favicon_image_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_favicon_for_branding', to='admin_backend_final.image')),
                ('logo', models.ForeignKey(blank=True, db_column='logo_image_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_logo_for_branding', to='admin_backend_final.image')),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Branding',
                'indexes': [models.Index(fields=['is_active'], name='admin_backe_is_acti_249acc_idx'), models.Index(fields=['site_title'], name='admin_backe_site_ti_d01d8f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_site_branding')],
            },
        ),
    ]
