# Generated by Django 5.2.4 on 2025-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0043_sitebranding'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sitebranding',
            name='unique_active_site_branding',
        ),
        migrations.RemoveIndex(
            model_name='sitebranding',
            name='admin_backe_is_acti_249acc_idx',
        ),
        migrations.RemoveIndex(
            model_name='sitebranding',
            name='admin_backe_site_ti_d01d8f_idx',
        ),
        migrations.RemoveField(
            model_name='sitebranding',
            name='is_active',
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='singleton_lock',
            field=models.CharField(db_index=True, default='X', editable=False, max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='site_title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
