# Generated by Django 5.2.4 on 2025-10-01 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0044_remove_sitebranding_unique_active_site_branding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1_title', models.CharField(blank=True, default='', max_length=255)),
                ('card1', models.TextField(blank=True, default='')),
                ('card2_title', models.CharField(blank=True, default='', max_length=255)),
                ('card2', models.TextField(blank=True, default='')),
                ('card3_title', models.CharField(blank=True, default='', max_length=255)),
                ('card3', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='admin_backend_final.product')),
            ],
        ),
    ]
