# Generated by Django 5.2.4 on 2025-10-02 19:15

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0045_productcards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='callbackrequest',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='callbackrequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='callbackrequest',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='approx_guest',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='budget',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='device_uuid',
            field=models.CharField(db_index=True, default='legacy', max_length=100),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='event_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='event_type',
            field=models.CharField(db_index=True, default='Other', max_length=120),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='event_venue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='phone_number',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='preferred_callback',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['device_uuid'], name='admin_backe_device__b93823_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['phone_number'], name='admin_backe_phone_n_412d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['status'], name='admin_backe_status_ee5cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['preferred_callback'], name='admin_backe_preferr_5ed92b_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['event_datetime'], name='admin_backe_event_d_801f24_idx'),
        ),
    ]
