# Generated by Django 5.2.4 on 2025-10-07 17:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0046_alter_callbackrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyDeletedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.CharField(db_index=True, max_length=100)),
                ('record_data', models.JSONField()),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.CharField(blank=True, default='', max_length=100)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDE', 'Hidden'), ('UNHIDE', 'Unhidden'), ('PERMANENT', 'Permanently Deleted')], db_index=True, default='VISIBLE', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admin_backend_final.recentlydeleteditem')),
            ],
            options={
                'indexes': [models.Index(fields=['table_name', 'record_id'], name='admin_backe_table_n_86ee37_idx'), models.Index(fields=['status'], name='admin_backe_status_3812e6_idx'), models.Index(fields=['deleted_at'], name='admin_backe_deleted_a3d634_idx')],
            },
        ),
    ]
